excalidraw_url:
  default: "https://excalidraw.com"
  type: enum
  choices:
    - "https://excalidraw.com"
    - "https://your-custom-excalidraw-instance.com"
  description: "Choose the Excalidraw URL to use."
